/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as ProductsProductIDRouteImport } from './routes/products/$productID'
import { Route as NotesAddRouteImport } from './routes/notes/add'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as NotesNoteIdEditRouteImport } from './routes/notes/$noteId.edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIDRoute = ProductsProductIDRouteImport.update({
  id: '/products/$productID',
  path: '/products/$productID',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesAddRoute = NotesAddRouteImport.update({
  id: '/notes/add',
  path: '/notes/add',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdEditRoute = NotesNoteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NotesNoteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes/$noteId': typeof NotesNoteIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/products/$productID': typeof ProductsProductIDRoute
  '/notes/': typeof NotesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes/$noteId': typeof NotesNoteIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/products/$productID': typeof ProductsProductIDRoute
  '/notes': typeof NotesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes/$noteId': typeof NotesNoteIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/products/$productID': typeof ProductsProductIDRoute
  '/notes/': typeof NotesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/notes/$noteId'
    | '/notes/add'
    | '/products/$productID'
    | '/notes/'
    | '/products/'
    | '/notes/$noteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/notes/$noteId'
    | '/notes/add'
    | '/products/$productID'
    | '/notes'
    | '/products'
    | '/notes/$noteId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/notes/$noteId'
    | '/notes/add'
    | '/products/$productID'
    | '/notes/'
    | '/products/'
    | '/notes/$noteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NotesNoteIdRoute: typeof NotesNoteIdRouteWithChildren
  NotesAddRoute: typeof NotesAddRoute
  ProductsProductIDRoute: typeof ProductsProductIDRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productID': {
      id: '/products/$productID'
      path: '/products/$productID'
      fullPath: '/products/$productID'
      preLoaderRoute: typeof ProductsProductIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/add': {
      id: '/notes/add'
      path: '/notes/add'
      fullPath: '/notes/add'
      preLoaderRoute: typeof NotesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId/edit': {
      id: '/notes/$noteId/edit'
      path: '/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof NotesNoteIdEditRouteImport
      parentRoute: typeof NotesNoteIdRoute
    }
  }
}

interface NotesNoteIdRouteChildren {
  NotesNoteIdEditRoute: typeof NotesNoteIdEditRoute
}

const NotesNoteIdRouteChildren: NotesNoteIdRouteChildren = {
  NotesNoteIdEditRoute: NotesNoteIdEditRoute,
}

const NotesNoteIdRouteWithChildren = NotesNoteIdRoute._addFileChildren(
  NotesNoteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NotesNoteIdRoute: NotesNoteIdRouteWithChildren,
  NotesAddRoute: NotesAddRoute,
  ProductsProductIDRoute: ProductsProductIDRoute,
  NotesIndexRoute: NotesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
